apiVersion: app/v1
kind: Deployment
metadata:
  name: system-depl
spec:
  selector:
    matchLabels:
      app: react-app
    replicas: 4
    template:
      metadata:
        labels:
          app: react-app
      spec:
        containers:
          -name: react-app
          image: janemurcomp/system
...
apiVersion: v1
kind: Service
metadata:
  name: system-srv
spec: 
  type: NodePort
  selectors:
    app: react-app
  ports: 
    -name: syst
    port: 5000
    targetPort: 5000